# ansible/playbook.yml

---
- name: "Setup GKE Cluster and Deploy Applications"
  hosts: local
  gather_facts: false
  vars_files:
    - vars/main.yml

  roles:
    - gke-setup
    - secrets-env
    - build-images
    - nginx-ingress
    - deploy-services
